/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Iteracao;

import javax.swing.JOptionPane;

/**
 *
 * @author Ruben Faria
 */
public class AdministradorLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdministradorLogin
     */
    public AdministradorLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSairA = new javax.swing.JButton();
        jButtonVoltarA = new javax.swing.JButton();
        jButtonLoginA = new javax.swing.JButton();
        jLabelUsernameA = new javax.swing.JLabel();
        jLabelPasswordA = new javax.swing.JLabel();
        jPasswordFieldPasswordA = new javax.swing.JPasswordField();
        jTextFieldUsernameA = new javax.swing.JTextField();
        jLabelImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 0));
        getContentPane().setLayout(null);

        jButtonSairA.setText("Sair");
        jButtonSairA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairAActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSairA);
        jButtonSairA.setBounds(400, 150, 71, 21);

        jButtonVoltarA.setText("Voltar a página anterior");
        jButtonVoltarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarAActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltarA);
        jButtonVoltarA.setBounds(220, 240, 150, 21);

        jButtonLoginA.setText("Login");
        jButtonLoginA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginAActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLoginA);
        jButtonLoginA.setBounds(320, 150, 57, 21);

        jLabelUsernameA.setText("Username:");
        getContentPane().add(jLabelUsernameA);
        jLabelUsernameA.setBounds(220, 60, 60, 20);

        jLabelPasswordA.setText("Password:");
        getContentPane().add(jLabelPasswordA);
        jLabelPasswordA.setBounds(220, 100, 60, 20);

        jPasswordFieldPasswordA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPasswordAActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldPasswordA);
        jPasswordFieldPasswordA.setBounds(290, 99, 130, 20);

        jTextFieldUsernameA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameAActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsernameA);
        jTextFieldUsernameA.setBounds(290, 59, 130, 20);

        jLabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/administrador-png.png"))); // NOI18N
        getContentPane().add(jLabelImagem);
        jLabelImagem.setBounds(-40, 10, 270, 290);

        setSize(new java.awt.Dimension(514, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldPasswordAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPasswordAActionPerformed

    private void jTextFieldUsernameAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameAActionPerformed

    private void jButtonLoginAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginAActionPerformed
        if(jTextFieldUsernameA.getText().equals("admin") && jPasswordFieldPasswordA.getText().equals("1234")) {
            AdministradorAmbiente tela3 = new AdministradorAmbiente();
            tela3.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Username ou Password incorretos");
        }
    }//GEN-LAST:event_jButtonLoginAActionPerformed

    private void jButtonVoltarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarAActionPerformed
        TelaEntrada tela = new TelaEntrada();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarAActionPerformed

    private void jButtonSairAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairAActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLoginA;
    private javax.swing.JButton jButtonSairA;
    private javax.swing.JButton jButtonVoltarA;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelPasswordA;
    private javax.swing.JLabel jLabelUsernameA;
    private javax.swing.JPasswordField jPasswordFieldPasswordA;
    private javax.swing.JTextField jTextFieldUsernameA;
    // End of variables declaration//GEN-END:variables
}
