/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Iteracao;

/**
 *
 * @author Ruben Faria
 */
public class LoginUtilizador extends javax.swing.JFrame {

    /**
     * Creates new form LoginUtilizador
     */
    public LoginUtilizador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldUsernameU = new javax.swing.JTextField();
        jPasswordFieldUsernameU = new javax.swing.JPasswordField();
        jButtonVoltarU = new javax.swing.JButton();
        jButtonSairU = new javax.swing.JButton();
        jButtonLoginU = new javax.swing.JButton();
        jLabelUsernameU = new javax.swing.JLabel();
        jLabelPasswordU = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jTextFieldUsernameU);
        jTextFieldUsernameU.setBounds(310, 80, 110, 19);
        getContentPane().add(jPasswordFieldUsernameU);
        jPasswordFieldUsernameU.setBounds(310, 120, 110, 19);

        jButtonVoltarU.setText("Voltar a página anterior");
        jButtonVoltarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarUActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltarU);
        jButtonVoltarU.setBounds(150, 260, 160, 21);

        jButtonSairU.setText("Sair");
        jButtonSairU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairUActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSairU);
        jButtonSairU.setBounds(390, 180, 50, 21);

        jButtonLoginU.setText("Login");
        jButtonLoginU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginUActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLoginU);
        jButtonLoginU.setBounds(300, 180, 57, 21);

        jLabelUsernameU.setText("Username:");
        getContentPane().add(jLabelUsernameU);
        jLabelUsernameU.setBounds(230, 80, 70, 13);

        jLabelPasswordU.setText("Password:");
        getContentPane().add(jLabelPasswordU);
        jLabelPasswordU.setBounds(230, 120, 60, 20);

        setSize(new java.awt.Dimension(514, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginUActionPerformed
        UtilizadorAmbiente tela1 = new UtilizadorAmbiente();
        tela1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLoginUActionPerformed

    private void jButtonVoltarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarUActionPerformed
        TelaEntrada tela = new TelaEntrada();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarUActionPerformed

    private void jButtonSairUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairUActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUtilizador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLoginU;
    private javax.swing.JButton jButtonSairU;
    private javax.swing.JButton jButtonVoltarU;
    private javax.swing.JLabel jLabelPasswordU;
    private javax.swing.JLabel jLabelUsernameU;
    private javax.swing.JPasswordField jPasswordFieldUsernameU;
    private javax.swing.JTextField jTextFieldUsernameU;
    // End of variables declaration//GEN-END:variables
}
