/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Iteracao;

/**
 *
 * @author Ruben Faria
 */
public class TelaEntrada extends javax.swing.JFrame {

    /**
     * Creates new form TelaEntrada
     */
    public TelaEntrada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEscolha = new javax.swing.JLabel();
        jLabelBemVindo = new javax.swing.JLabel();
        jButtonUTILIZADOR = new javax.swing.JButton();
        jButtonADMINISTRADOR = new javax.swing.JButton();
        TelaEntrada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelEscolha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEscolha.setText("Qual a sua função?");
        getContentPane().add(jLabelEscolha);
        jLabelEscolha.setBounds(200, 150, 180, 30);

        jLabelBemVindo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelBemVindo.setText("Hospital Suicidio");
        getContentPane().add(jLabelBemVindo);
        jLabelBemVindo.setBounds(180, 40, 190, 60);

        jButtonUTILIZADOR.setText("UTILIZADOR");
        jButtonUTILIZADOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUTILIZADORActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUTILIZADOR);
        jButtonUTILIZADOR.setBounds(320, 220, 160, 100);

        jButtonADMINISTRADOR.setText("ADMINISTRADOR");
        jButtonADMINISTRADOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADMINISTRADORActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonADMINISTRADOR);
        jButtonADMINISTRADOR.setBounds(80, 220, 160, 100);

        TelaEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FUNDO-login.jpg"))); // NOI18N
        getContentPane().add(TelaEntrada);
        TelaEntrada.setBounds(0, 0, 560, 400);

        setSize(new java.awt.Dimension(574, 437));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonADMINISTRADORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADMINISTRADORActionPerformed
        AdministradorLogin tela1 = new AdministradorLogin();
        tela1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonADMINISTRADORActionPerformed

    private void jButtonUTILIZADORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUTILIZADORActionPerformed
        LoginUtilizador tela2 = new LoginUtilizador();
        tela2.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonUTILIZADORActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelaEntrada;
    private javax.swing.JButton jButtonADMINISTRADOR;
    private javax.swing.JButton jButtonUTILIZADOR;
    private javax.swing.JLabel jLabelBemVindo;
    private javax.swing.JLabel jLabelEscolha;
    // End of variables declaration//GEN-END:variables
}
